# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('foto_proposito', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/')),
                ('texto_corto_proposito', models.TextField(blank=True, null=True)),
                ('foto_fondo_index_aprendizaje', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/')),
                ('foto_fondo_footer', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/')),
                ('anio_copyright', models.CharField(max_length=50, verbose_name='A\xf1o del Copyright')),
                ('foto_fondo_flatpage', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/')),
                ('foto_fondo_noticias', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/')),
                ('foto_fondo_aprende', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/')),
                ('foto_fondo_documentos', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/')),
                ('foto_fondo_videos', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/')),
                ('foto_fondo_audios', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/')),
                ('foto_fondo_galerias', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/')),
            ],
            options={
                'verbose_name': 'Configuraci\xf3n del sitio',
            },
        ),
    ]
