# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 19:54
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='foto_fondo_eventos',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/'),
        ),
    ]
