# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-02 16:06
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_siteconfiguration_foto_fondo_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='foto_fondo_vida',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='foto/proposito/'),
        ),
    ]
